species_mapping = {
'Norway spruce':'Norway spruce',
'sitka spruce':'Norway spruce',
'other spruces':'Norway spruce',
'Scots pine':'Pinus sylvestris',
'mountain pine':'Pinus spp.',
'European black pine':'Pinus nigra var nigra',
'Pinus cembra':'Pinus sylvestris',
'eastern white pine':'Pinus sylvestris',
'other pines':'Pinus sylvestris',
'silver fir':'Abies alba',
'Grand fir':'Abies grandis',
'other firs':'Abies alba',
'Douglas fir':'Pseudotsuga menziesii',
'European larch':'Larix decidua',
'Japanese larch':'Larix decidua',
'other coniferous trees':'Pinus spp.',
'European yew':'Thuja pilicata',
'beech':'Fagus spp.',
'English oak':'Quercus robur',
'sessile oak':'Quercus spp.',
'Northern red oak':'Quercus rubra',
'common ash':'Fraxinus exselsior',
'hornbeam':'Carpinus spp.',
'sycamore maple':'Acer pseudoplatanus',
'Norway maple':'Acer pseudoplatanus',
'field maple':'Acer pseudoplatanus',
'linden tree':'Tilia cordata',
'black locust':'Acer pseudoplatanus',
'elm, native species':'Ulmus spp.',
'chestnut':'Quercus spp.',
'misc. deciduous trees with long life expectancy':'Quercus spp.',
'service tree':'Sorbus aucuparia',
'common whitebeam':'Sorbus aucuparia',
'silver birch':'Betula pendula',
'Betula pubescens + Betula pubescens var. glabrata':'Betula spp.',
'black alder':'Alnus glutinosa',
'grey alder':'Alnus incana',
'common aspen':'Populus tremula',
'European black poplar':'Populus spp.',
'grey poplar':'Populus spp.',
'silver poplar':'Populus spp.',
'balsam poplar':'Populus spp.',
'European rowan':'Populus spp.',
'willow':'Salix caprea',
'bird cherry':'Prunus avium',
'wild cherry':'Prunus avium',
'black cherry':'Prunus avium',
'misc. deciduous trees with short life expectancy':'Populus spp.',
'European crab apple':'Prunus avium',
'European wild pear':'Prunus avium',
'wild service tree':'Sorbus aucuparia'
}